plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tweaks.utility'
    compileSdk 34

    defaultConfig {
        applicationId "com.tweaks.utility"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
        
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.22.1'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
